### PR TITLE
Configuration files and Dockerfiles for every parts of the project

### PR DESCRIPTION
**Pull request by telliere**
In addition to that, I implemented the usage of a configuration file for the server, allowing user to set vault's path, spire-server informations at runtime.

### CODE REVIEW

**Review by mmatthiesencsc — APPROVED** [review]
Looks good.

**Comment by telliere** [comment]
At the end of the day, I implemented configuration file for the client (common for the 3 sub-programs) allowing :
- Configuration of the vault address
- Configuration of the hpcs server address
- Configuration of the supercomputer (currently not fully used)
- Configuration of the spire server (address, port and trust domain)

and one for the server : 
- Configuration of the vault address
- Configuration of the spire server (address, port and trust domain)

**Comment by telliere** [comment]
Last bits about `age` and `gocryptfs` static binaries are available, ready to merge

**Review by mmatthiesencsc — APPROVED** [review]
I went though the code again. If you have time next week, moving the black / newline tools here would be good, but now I think the documentation is more important. Great work!

**Pull request merged**
